////////////////////////////////////////////////////////////////////////////////
//
// Juan Manuel Fajardo Sarmiento
// Francisco Javier Caracuel Beltrán
//
// Nuevos Paradigmas de Interacción - Ciencias de la Computación e Inteligencia
// Artificial
//
// UGR - GII
//
// Curso 2017-2018
//
// Gallery
//
// JFrame que contiene la interfaz gráfica para mostrar los personajes
//
////////////////////////////////////////////////////////////////////////////////
package serverpc;

import java.awt.event.ActionEvent;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.Timer;

public class Gallery extends javax.swing.JFrame {

    // Nombre del personaje actual
    private String name;

    // Ruta del fichero del personaje
    private String path;

    // Variable utilizada para cambiar el color al borde de la selección de
    // la imagen
    private boolean select;

    /**
     * Creates new form Gallery
     */
    public Gallery() {
        initComponents();

        //setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);
        // Se centra la ventana
        setLocationRelativeTo(null);

        // Comienza sin estar seleccionada la imagen
        select = false;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSelect = new javax.swing.JPanel();
        jLabelSelect = new javax.swing.JLabel();
        jPanelImage = new javax.swing.JPanel();
        jLabelImage = new javax.swing.JLabel();
        jPanelName = new javax.swing.JPanel();
        jLabelName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agentes Conversacionales - NPI - JMFS - FJCB");

        jPanelSelect.setLayout(new java.awt.BorderLayout());

        jLabelSelect.setFont(new java.awt.Font("Bodoni MT", 0, 12)); // NOI18N
        jLabelSelect.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSelect.setText("Selecciona un personaje:");
        jPanelSelect.add(jLabelSelect, java.awt.BorderLayout.CENTER);

        jPanelImage.setLayout(new java.awt.BorderLayout());

        jLabelImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/000.jpg"))); // NOI18N
        jPanelImage.add(jLabelImage, java.awt.BorderLayout.CENTER);

        jPanelName.setLayout(new java.awt.BorderLayout());

        jLabelName.setFont(new java.awt.Font("Bodoni MT", 0, 24)); // NOI18N
        jLabelName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelName.setText("Ibn al-Jatib");
        jPanelName.add(jLabelName, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelImage, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                    .addComponent(jPanelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelSelect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelImage, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelSelect;
    private javax.swing.JPanel jPanelImage;
    private javax.swing.JPanel jPanelName;
    private javax.swing.JPanel jPanelSelect;
    // End of variables declaration//GEN-END:variables

    // Se cambia la imagen que se está mostrando en la galería
    public void setImage(String name, String file) {

        this.name = name;
        this.path = file;

        // Se cambia el nombre del personaje que se quiere mostrar
        jLabelName.setText(name);

        // Se cambia el icono del personaje que se quiere mostrar
        jLabelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource(file)));

        // Al cambiar de personaje se elimina el borde
        jLabelImage.setBorder(null);

        // Se indica que no ha sido seleccionado
        select = false;

    }

    public void selectImage() {

        java.awt.Color color;

        if (select) {
            color = new java.awt.Color(30, 144, 255);
        } else {
            color = new java.awt.Color(150, 150, 150);
        }

        jLabelImage.setBorder(new javax.swing.border.LineBorder(color, 2, true));

        // Si ha sido re-seleccionado se muestra el mensaje indicando que se
        // inicia la conversación con el agente
        if (select) {
            showMessage("Personaje seleccionado", "Iniciando la conversación...");
        }

        // Se cambia la selección
        select = !select;

    }

    private void showMessage(String title, String message) {

        JOptionPane pane = new JOptionPane(message,
                JOptionPane.INFORMATION_MESSAGE);
        JDialog dialog = pane.createDialog(null, title);
        dialog.setModal(false);
        dialog.setVisible(true);

        new Timer(5000, (ActionEvent e) -> {
            dialog.setVisible(false);
        }).start();

    }

}
